apiVersion: v1
kind: Service
metadata:
  name: mysql-server
spec:
  selector:
    app: database-app  # Selects pods with the label 'app=flask-app-pod'
  ports:
    - name: mysql
      protocol: TCP
      port: 3306  # Service port
      targetPort: 3306
