apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
  labels:
    app: flask-app	
spec:
  containers:
  - name: vasecom-appv1
    image: devopsengineer400/flaskapp:build_no
    ports:
    - containerPort: 5000  # adjust the port as per your Flask app configuration
  # Add an environment variable to configure Flask to connect to the database
  imagePullSecrets:
  - name: my-docker-secret
