apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app  # Selects pods with the label 'app=flask-app-pod'
  ports:
    - name: flask
      protocol: TCP
      port: 5001  # Service port
      targetPort: 5000
      nodePort: 30009  # NodePort - Externally accessible port on nodes
  type: NodePort
